FROM openjdk:12

COPY kafkaproj-play-1.0-SNAPSHOT.jar /usr/app/kafkaproj-play/kafkaproj-play-1.0-SNAPSHOT.jar
WORKDIR /usr/app/kafkaproj-play
ENTRYPOINT ["java","-jar","kafkaproj-play-1.0-SNAPSHOT.jar"]
